-- =====================================================
-- INSERTAR TODOS LOS 22 EJERCICIOS COMPLETOS CON GOOGLE DRIVE URLs
-- Script completo para VitalApp
-- =====================================================

-- Insertar todos los ejercicios con sus datos completos y URLs de Google Drive
INSERT INTO exercises (name, description, instructions, duration_seconds, repetitions, sets, video_url, image_url, category_id, intensity_id, exercise_type_id, benefits, safety_tips, modifications, created_at) VALUES

-- 6. Elevación de Talones y Puntas
('Elevación de Talones y Puntas',
'Ejercicio para fortalecer pantorrillas y músculos del pie, mejorando equilibrio y circulación.',
'1. Párate derecho con apoyo de silla o pared\n2. Levanta lentamente los talones del suelo\n3. Mantén 2 segundos en puntas\n4. Baja lentamente\n5. Repite de forma controlada',
NULL, 12, 2,
'https://drive.google.com/file/d/1IRb5e6PHvtQj6cxkieeuGE-u_ehkNX5A/preview',
'https://drive.google.com/uc?export=view&id=1IRb5e6PHvtQj6cxkieeuGE-u_ehkNX5A',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Suave'),
(SELECT id FROM exercise_types WHERE name = 'Funcional'),
'Fortalece pantorrillas, mejora equilibrio, estimula circulación en piernas',
'Usar apoyo para equilibrio, superficie antideslizante, no forzar altura',
'Alternar un pie por vez, reducir rango si hay molestias',
NOW()),

-- 7. Elevación Lateral de Pierna
('Elevación Lateral de Pierna',
'Ejercicio para fortalecer músculos abductores y mejorar estabilidad lateral de cadera.',
'1. Párate derecho con apoyo de silla\n2. Levanta una pierna hacia el lado\n3. Mantén tronco erguido\n4. Baja lentamente\n5. Alterna entre piernas',
NULL, 8, 2,
'https://drive.google.com/file/d/1J6sxowcvmAJxo1A8S6aooPnm8S-fm05H/preview',
'https://drive.google.com/uc?export=view&id=1J6sxowcvmAJxo1A8S6aooPnm8S-fm05H',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Funcional'),
'Fortalece abductores, mejora estabilidad pélvica, previene dolores de espalda',
'Mantener tronco erguido, no balancearse, usar apoyo constante',
'Reducir altura de elevación, aumentar apoyo si es necesario',
NOW()),

-- 8. Equilibrio sobre un Pie
('Equilibrio sobre un Pie',
'Ejercicio específico para mejorar equilibrio estático y fortalecer músculos estabilizadores.',
'1. Párate junto a una pared o silla\n2. Levanta un pie del suelo\n3. Mantén equilibrio todo el tiempo posible\n4. Usa apoyo solo si es necesario\n5. Alterna entre pies',
30, NULL, 3,
'https://drive.google.com/file/d/1Pu077sE3QL22e1MX-SITjVQ2MGT5LdOp/preview',
'https://drive.google.com/uc?export=view&id=1Pu077sE3QL22e1MX-SITjVQ2MGT5LdOp',
(SELECT id FROM categories WHERE name = 'Equilibrio'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Equilibrio'),
'Mejora equilibrio estático, fortalece músculos del pie, previene caídas',
'Tener apoyo cerca, superficie estable, progresar gradualmente',
'Comenzar con apoyo ligero, reducir tiempo inicial',
NOW()),

-- 9. Estiramiento de Gato-Vaca (Sentado)
('Estiramiento de Gato-Vaca (Sentado)',
'Ejercicio de movilidad espinal adaptado para realizar sentado, mejora flexibilidad de columna.',
'1. Siéntate al borde de una silla\n2. Coloca manos en rodillas\n3. Arquea espalda mirando hacia arriba (vaca)\n4. Redondea espalda mirando hacia abajo (gato)\n5. Alterna lentamente',
300, NULL, NULL,
'https://drive.google.com/file/d/1SH_qLOr5jaFQyiUTCY1-FjNcN5TmSS_x/preview',
'https://drive.google.com/uc?export=view&id=1SH_qLOr5jaFQyiUTCY1-FjNcN5TmSS_x',
(SELECT id FROM categories WHERE name = 'Flexibilidad'),
(SELECT id FROM intensities WHERE name = 'Suave'),
(SELECT id FROM exercise_types WHERE name = 'Estiramiento'),
'Mejora movilidad espinal, alivia tensión en espalda, reduce rigidez',
'Movimientos lentos y controlados, no forzar rango de movimiento',
'Reducir amplitud de movimiento si hay molestias',
NOW()),

-- 10. Extensión de Cuadríceps
('Extensión de Cuadríceps',
'Ejercicio para fortalecer músculos frontales del muslo, importante para caminar y levantarse.',
'1. Siéntate en una silla con espalda recta\n2. Extiende lentamente una pierna\n3. Mantén 3 segundos\n4. Baja lentamente sin tocar el suelo\n5. Alterna entre piernas',
NULL, 10, 2,
'https://drive.google.com/file/d/1Sr0WC4sOy1SWIEd3GoeAFwbrod5q4ZaZ/preview',
'https://drive.google.com/uc?export=view&id=1Sr0WC4sOy1SWIEd3GoeAFwbrod5q4ZaZ',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Resistencia'),
'Fortalece cuadríceps, mejora función de rodilla, facilita levantarse',
'Mantener espalda apoyada, no bloquear rodilla completamente',
'Reducir rango de extensión, usar menos repeticiones',
NOW()),

-- 11. Flexiones en la Pared (Wall Push-up)
('Flexiones en la Pared (Wall Push-up)',
'Ejercicio de fortalecimiento para brazos, pecho y hombros adaptado para adultos mayores.',
'1. Párate a un brazo de distancia de la pared\n2. Coloca palmas contra la pared a altura del pecho\n3. Flexiona brazos acercándote a la pared\n4. Empuja para volver a posición inicial\n5. Mantén cuerpo recto',
NULL, 8, 2,
'https://drive.google.com/file/d/1_RT3mZ4cLctx1JLk6L_bYwUorCvy7Lih/preview',
'https://drive.google.com/uc?export=view&id=1_RT3mZ4cLctx1JLk6L_bYwUorCvy7Lih',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Resistencia'),
'Fortalece pecho, hombros y tríceps, mejora fuerza funcional de brazos',
'Mantener cuerpo alineado, no acercar demasiado la cara a la pared',
'Aumentar distancia de la pared para menor intensidad',
NOW()),

-- 12. Jumping Jacks sin Salto
('Jumping Jacks sin Salto',
'Ejercicio cardiovascular de bajo impacto que simula jumping jacks tradicionales.',
'1. Párate con pies juntos y brazos a los lados\n2. Da un paso lateral mientras subes brazos\n3. Regresa pies juntos bajando brazos\n4. Alterna lados de forma rítmica\n5. Mantén movimiento continuo',
300, NULL, NULL,
'https://drive.google.com/file/d/1_WieqLriX9ccZWIeiuZ3Po41Iyhz0YFe/preview',
'https://drive.google.com/uc?export=view&id=1_WieqLriX9ccZWIeiuZ3Po41Iyhz0YFe',
(SELECT id FROM categories WHERE name = 'Cardio'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Aeróbico'),
'Mejora capacidad cardiovascular, coordina extremidades, bajo impacto',
'Superficie antideslizante, mantener ritmo cómodo, parar si hay fatiga',
'Reducir amplitud de brazos, hacer movimiento más lento',
NOW()),

-- 13. Marcha en el Sitio
('Marcha en el Sitio',
'Ejercicio cardiovascular básico que simula caminar sin desplazamiento.',
'1. Párate derecho con brazos relajados\n2. Levanta una rodilla como si caminaras\n3. Alterna piernas de forma rítmica\n4. Balancea brazos naturalmente\n5. Mantén postura erguida',
300, NULL, NULL,
'https://drive.google.com/file/d/1h784l-aYYANrX02al64zGZPjL5DM_mVb/preview',
'https://drive.google.com/uc?export=view&id=1h784l-aYYANrX02al64zGZPjL5DM_mVb',
(SELECT id FROM categories WHERE name = 'Cardio'),
(SELECT id FROM intensities WHERE name = 'Suave'),
(SELECT id FROM exercise_types WHERE name = 'Aeróbico'),
'Mejora coordinación, activa sistema cardiovascular, bajo impacto articular',
'Mantener equilibrio, no levantar rodillas demasiado alto al inicio',
'Reducir altura de las rodillas, usar apoyo si es necesario',
NOW()),

-- 14. Paso Lateral
('Paso Lateral',
'Ejercicio que combina fortalecimiento y equilibrio mediante pasos controlados hacia los lados.',
'1. Párate con pies separados al ancho de hombros\n2. Da un paso lateral amplio con una pierna\n3. Lleva la otra pierna para juntar pies\n4. Repite hacia el mismo lado\n5. Cambia dirección después de serie',
240, NULL, NULL,
'https://drive.google.com/file/d/1hCyporUKsOIuFiHz7PE3CfocJf-SYkUV/preview',
'https://drive.google.com/uc?export=view&id=1hCyporUKsOIuFiHz7PE3CfocJf-SYkUV',
(SELECT id FROM categories WHERE name = 'Equilibrio'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Funcional'),
'Mejora estabilidad lateral, fortalece piernas, mejora coordinación',
'Superficie estable, pasos controlados, tener apoyo disponible',
'Reducir amplitud del paso, usar baranda para apoyo',
NOW()),

-- 15. Peso muerto con mancuernas
('Peso muerto con mancuernas',
'Ejercicio avanzado de fortalecimiento para espalda baja, glúteos y piernas.',
'1. Párate con pies al ancho de hombros sosteniendo mancuernas\n2. Mantén espalda recta\n3. Flexiona caderas empujándolas hacia atrás\n4. Baja mancuernas manteniendo cerca del cuerpo\n5. Regresa a posición inicial',
NULL, 6, 2,
'https://drive.google.com/file/d/1hUHxF3iDZ_2jGViFT3H6cqlaLS7SwkJ1/preview',
'https://drive.google.com/uc?export=view&id=1hUHxF3iDZ_2jGViFT3H6cqlaLS7SwkJ1',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Intermedio'),
(SELECT id FROM exercise_types WHERE name = 'Resistencia'),
'Fortalece cadena posterior, mejora postura, fortalece core',
'Mantener espalda neutra, no redondear columna, peso apropiado',
'Usar peso más liviano, reducir rango de movimiento',
NOW()),

-- 16. Puñetazos al Aire
('Puñetazos al Aire',
'Ejercicio cardiovascular que combina movimiento de brazos con activación del core.',
'1. Párate con pies separados, rodillas ligeramente flexionadas\n2. Puños cerrados a altura del pecho\n3. Extiende un brazo como dando un puñetazo\n4. Alterna brazos de forma rítmica\n5. Mantén core activado',
300, NULL, NULL,
'https://drive.google.com/file/d/1j01Wd6X_Atzn3sgta5sp4iow6o-JmM1X/preview',
'https://drive.google.com/uc?export=view&id=1j01Wd6X_Atzn3sgta5sp4iow6o-JmM1X',
(SELECT id FROM categories WHERE name = 'Cardio'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Aeróbico'),
'Mejora coordinación, activa sistema cardiovascular, fortalece brazos',
'No extender completamente los brazos, mantener control en todo momento',
'Reducir velocidad y intensidad, hacer movimientos más pequeños',
NOW()),

-- 17. Remo con barra
('Remo con barra',
'Ejercicio de fortalecimiento para músculos de la espalda y brazos usando barra.',
'1. Párate con pies al ancho de hombros sosteniendo barra\n2. Inclínate ligeramente hacia adelante\n3. Tira de la barra hacia el abdomen\n4. Mantén codos cerca del cuerpo\n5. Baja controladamente',
NULL, 8, 3,
'https://drive.google.com/file/d/1qy7qToU3n44lJT2IJT-lBfEW_rKoQ7gA/preview',
'https://drive.google.com/uc?export=view&id=1qy7qToU3n44lJT2IJT-lBfEW_rKoQ7gA',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Intermedio'),
(SELECT id FROM exercise_types WHERE name = 'Resistencia'),
'Fortalece espalda media y alta, mejora postura, equilibra musculatura',
'Mantener espalda recta, no usar impulso, peso apropiado',
'Usar peso más liviano, reducir rango de movimiento',
NOW()),

-- 18. Remo con Banda Elástica (si tienes)
('Remo con Banda Elástica (si tienes)',
'Ejercicio de fortalecimiento para espalda usando banda elástica como resistencia.',
'1. Siéntate con piernas extendidas\n2. Coloca banda alrededor de los pies\n3. Tira de la banda hacia el abdomen\n4. Mantén espalda recta\n5. Regresa controladamente',
NULL, 12, 2,
'https://drive.google.com/file/d/1uF9DfCtDFOA1teTO4K9LjgXrfG4naiKf/preview',
'https://drive.google.com/uc?export=view&id=1uF9DfCtDFOA1teTO4K9LjgXrfG4naiKf',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Resistencia'),
'Fortalece músculos de la espalda, mejora postura, resistencia ajustable',
'Mantener tensión constante en la banda, no permitir que se suelte bruscamente',
'Usar banda de menor resistencia, reducir rango de movimiento',
NOW()),

-- 19. Rotación de Cuello
('Rotación de Cuello',
'Ejercicio suave de movilidad para mantener flexible la zona cervical.',
'1. Siéntate o párate con espalda recta\n2. Gira lentamente la cabeza hacia la derecha\n3. Regresa al centro\n4. Gira hacia la izquierda\n5. Movimientos lentos y controlados',
180, 5, 1,
'https://drive.google.com/file/d/1uarQnmcFWA09fLSWxHXVOlJmyvZBXxsJ/preview',
'https://drive.google.com/uc?export=view&id=1uarQnmcFWA09fLSWxHXVOlJmyvZBXxsJ',
(SELECT id FROM categories WHERE name = 'Movilidad'),
(SELECT id FROM intensities WHERE name = 'Muy Suave'),
(SELECT id FROM exercise_types WHERE name = 'Estiramiento'),
'Mantiene movilidad cervical, alivia tensión del cuello, mejora flexibilidad',
'Movimientos muy lentos, no forzar rango, parar si hay mareo',
'Reducir rango de rotación, hacer solo hacia un lado si es más cómodo',
NOW()),

-- 20. Sentadilla
('Sentadilla',
'Ejercicio fundamental para fortalecer piernas y glúteos, versión adaptada para adultos mayores.',
'1. Párate frente a una silla con pies separados\n2. Baja como si fueras a sentarte\n3. Detente justo antes de tocar la silla\n4. Regresa a posición de pie\n5. Usa la silla como referencia',
NULL, 8, 2,
'https://drive.google.com/file/d/1vUQbZSy_e1QeZTUj32FFO0iyBi40-41N/preview',
'https://drive.google.com/uc?export=view&id=1vUQbZSy_e1QeZTUj32FFO0iyBi40-41N',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Intermedio'),
(SELECT id FROM exercise_types WHERE name = 'Funcional'),
'Fortalece piernas y glúteos, mejora función de levantarse, aumenta independencia',
'Mantener peso en talones, rodillas alineadas con pies, usar silla como guía',
'Sentarse completamente en la silla si es necesario, usar apoyo de brazos',
NOW()),

-- 21. Sentarse y Levantarse de una Silla (Chair Squat)
('Sentarse y Levantarse de una Silla (Chair Squat)',
'Ejercicio funcional que practica el movimiento esencial de sentarse y levantarse.',
'1. Párate frente a una silla resistente\n2. Siéntate lentamente en la silla\n3. Levántate sin usar las manos si es posible\n4. Controla el movimiento en ambas direcciones\n5. Repite de forma controlada',
NULL, 10, 2,
'https://drive.google.com/file/d/1yPI4qOE-WOLTTGpzp9tam7Am6z6Sp-EG/preview',
'https://drive.google.com/uc?export=view&id=1yPI4qOE-WOLTTGpzp9tam7Am6z6Sp-EG',
(SELECT id FROM categories WHERE name = 'Fortalecimiento'),
(SELECT id FROM intensities WHERE name = 'Moderado'),
(SELECT id FROM exercise_types WHERE name = 'Funcional'),
'Fortalece piernas, practica movimiento funcional, mejora independencia',
'Silla resistente y estable, usar brazos de silla si es necesario',
'Permitir uso de brazos para apoyo, silla más alta si es necesario',
NOW()),

-- 22. Torsión Suave de Columna (Sentado)
('Torsión Suave de Columna (Sentado)',
'Ejercicio de movilidad espinal que mejora la rotación de la columna vertebral.',
'1. Siéntate en el borde de una silla\n2. Coloca manos en hombros opuestos\n3. Gira lentamente el tronco hacia un lado\n4. Regresa al centro\n5. Repite hacia el otro lado',
240, 5, 1,
'https://drive.google.com/file/d/1yvNBjUb0zZ3VM1bu6ERSRNF0j05gkj2k/preview',
'https://drive.google.com/uc?export=view&id=1yvNBjUb0zZ3VM1bu6ERSRNF0j05gkj2k',
(SELECT id FROM categories WHERE name = 'Movilidad'),
(SELECT id FROM intensities WHERE name = 'Suave'),
(SELECT id FROM exercise_types WHERE name = 'Estiramiento'),
'Mejora rotación espinal, alivia rigidez de espalda, mantiene flexibilidad',
'Mantener pelvis estable, no forzar rotación, movimientos lentos',
'Reducir rango de rotación, hacer solo hacia un lado si es más cómodo',
NOW());

-- Verificar que todos los ejercicios se insertaron
SELECT 'Total de ejercicios en la base de datos:' as mensaje, COUNT(*) as cantidad FROM exercises;

-- Mostrar resumen por categoría
SELECT 
    c.name as 'Categoría',
    COUNT(e.id) as 'Ejercicios',
    GROUP_CONCAT(e.name ORDER BY e.name SEPARATOR ', ') as 'Nombres'
FROM categories c
LEFT JOIN exercises e ON c.id = e.category_id
GROUP BY c.id, c.name
ORDER BY COUNT(e.id) DESC;